apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: example-secret
  namespace: default
spec:
  encryptedData:
    key: AgAZzgTPBKpiKa5er1V+YZL1RVEDFPny/PnoWT2uBqLW1j+Fgd76VgEOuZQr8txc4tgzSZjGnNNEUbTIRYgJkbVLz257iJkPZEyreeVPKnB4J2+nk+c60Bm332l5DczVkOwgD44Y7ZnhShhGoHiOtGHl20bdjxKGFi/3oyX1oHYRJYwOXO/DlmQRQU08V48So+IPs2T+NNo56FYpYxxd+znaQFlt8/BgUrYYxQq4hgiqUUV6lJUOJhyYcvKrX8p0VhnDsXSfXwFwwBego+SeYNXb3OBObe5sVyPUqvbtiyj83+Y0kI8vAzC+FJJLacv7UZqAeT5DEc8e/QmpR8y97ALv2wxsGGn7WDw+y15u44xiXFAtB1exY1LqQkOw/unSvfLfEFtMvrcZn1iuJidPxKXJe8RbwSzjf+4yAqRpwi9Z+RzWGqbXTd7QokI4UxfopTlljRQzKlH1jlDheJvyz1nXpRpjZMaI0HryfEGubqAy7UVHRTjuXYUOwU39OcxBJ//mV7ggCnIaJ4yoPTDxcuaOVmmyibX83LS3yUnbOSthtQv5DgxkjCbf4wBCqjwbrdjgaF0BCedUMSAp+qREOqczakaL6BXe6iCY0cdLFcZxydQ93UdfxCFBkU2nESbd40Jr6FtrPkiL0W8BJ0QckUZE7KrZO/oSraahMmWQGhlbswFvusG1227K/SrcRCPZZCAI7Agm1w==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: example-secret
      namespace: default
    type: Opaque
